INSERT INTO STUDENT_MODEL(CPF, EMAIL, NAME) VALUES ('07983136927', '123@GMAIL.COM', 'GIOVANNI');
INSERT INTO STUDENT_MODEL(CPF, EMAIL, NAME) VALUES ('07981111127', '456@GMAIL.COM', 'NATHALY');

INSERT INTO MATERIAL_MODEL(CONTENT, FILE_NAME, ID_TEACHER) VALUES ('CONTEUDO', 'ARQUIVO.PDF', '50509');
INSERT INTO MATERIAL_MODEL(CONTENT, FILE_NAME, ID_TEACHER) VALUES ('CONTEUDO1', '23.PDF', '50509');
INSERT INTO MATERIAL_MODEL(CONTENT, FILE_NAME, ID_TEACHER) VALUES ('CONTEUDO2', 'APOSTILA.PDF', '50519');

INSERT INTO TEACHER_MODEL(DTYPE, CPF, EMAIL, ID_DISCIPLINE, NOME, AMOUNT_CERTIFIED) VALUES ('COISA', '079.831.369-27', 'EMAIL@GMAIL.COM', 509071355, 'não sei', 5050);
INSERT INTO TEACHER_MODEL(DTYPE, CPF, EMAIL, ID_DISCIPLINE, NOME, AMOUNT_CERTIFIED) VALUES ('COISA', '079.831.369-27', 'EMAIL1@GMAIL.COM', 509071352, 'não sei', 5052);
INSERT INTO TEACHER_MODEL(DTYPE, CPF, EMAIL, ID_DISCIPLINE, NOME, AMOUNT_CERTIFIED) VALUES ('COISA', '079.831.88822', 'EMAIL123@GMAIL.COM', 509071351, 'não sei', 5051);

INSERT INTO SUBJECT_MODEL(AMOUNT_ACCESS, DESCPTION, ID_DSCIPLINE) VALUES (105030, 'vamos estudar cambada', 1234567);

INSERT INTO DISCIPLINE_MODEL (DESCRPTION_DISCIPLINE, NAME_DISCIPLINE) VALUES ('oi', 'Prog tbm');
INSERT INTO DISCIPLINE_MODEL (DESCRPTION_DISCIPLINE, NAME_DISCIPLINE) VALUES ('oi2', 'Prog tbm2');
INSERT INTO DISCIPLINE_MODEL (DESCRPTION_DISCIPLINE, NAME_DISCIPLINE) VALUES ('oi2', 'Prog tbm3');


INSERT INTO TEST_MODEL (NAME, ANSWERS, DATE_TIME) VALUES ('Prova de sip', '{"1":"C","2":"A","3":"D"}', TO_DATE('2023-04-11', 'yyyy-mm-dd'));
INSERT INTO TEST_MODEL (NAME, ANSWERS, DATE_TIME) VALUES ('Prova de The Winter', '{"1":"D","2":"E","3":"C"}',TO_DATE('2023-05-17', 'yyyy-mm-dd'));
INSERT INTO TEST_MODEL (NAME, ANSWERS, DATE_TIME) VALUES ('Prova de Sum', '{"1":"C","2":"A","3":"B"}', TO_DATE('2023-06-15', 'yyyy-mm-dd'));




