INSERT INTO ROLE_MODEL(ROLE) VALUES ('ROLE_TEACHER');
INSERT INTO ROLE_MODEL(ROLE) VALUES ('ROLE_STUDENT');
INSERT INTO ROLE_MODEL(ROLE) VALUES ('ROLE_CERTIFIER');
INSERT INTO ROLE_MODEL(ROLE) VALUES ('ROLE_ADMIN');


INSERT INTO CLIENT_MODEL(NAME, LOGIN, PASSWORD) VALUES ('Renan','renan','$2a$10$224Y56.QHRu.7XDU9CwlG.ZMfVWUWm0YBvslnF.hdmsKXTJlgb/YK');
INSERT INTO STUDENT_MODEL(CPF, EMAIL, NAME, CLIENT_ID) VALUES ('07983136927', '123@GMAIL.COM', 'Renan', 1);
INSERT INTO CLIENT_ROLE(CLIENT_ID, ROLE_ID) VALUES (1, 1);

INSERT INTO CLIENT_MODEL(NAME, LOGIN, PASSWORD) VALUES ('Giovani','giovani','$2a$10$224Y56.QHRu.7XDU9CwlG.ZMfVWUWm0YBvslnF.hdmsKXTJlgb/YK');
INSERT INTO STUDENT_MODEL(CPF, EMAIL, NAME, CLIENT_ID) VALUES ('07983136928', '789@GMAIL.COM', 'GIOVANNI', 2);
INSERT INTO CLIENT_ROLE(CLIENT_ID, ROLE_ID) VALUES (2, 2);

INSERT INTO CLIENT_MODEL(NAME, LOGIN, PASSWORD) VALUES ('Alguem','alguem','$2a$10$224Y56.QHRu.7XDU9CwlG.ZMfVWUWm0YBvslnF.hdmsKXTJlgb/YK');
INSERT INTO STUDENT_MODEL(CPF, EMAIL, NAME, CLIENT_ID) VALUES ('07983136929', '456@GMAIL.COM', 'Alguem', 3);
INSERT INTO CLIENT_ROLE(CLIENT_ID, ROLE_ID) VALUES (3, 3);


INSERT INTO MATERIAL_MODEL(CONTENT, FILE_NAME, ID_TEACHER) VALUES ('CONTEUDO', 'ARQUIVO.PDF', '50509');
INSERT INTO MATERIAL_MODEL(CONTENT, FILE_NAME, ID_TEACHER) VALUES ('CONTEUDO1', '23.PDF', '50509');
INSERT INTO MATERIAL_MODEL(CONTENT, FILE_NAME, ID_TEACHER) VALUES ('CONTEUDO2', 'APOSTILA.PDF', '50519');

INSERT INTO TEACHER_MODEL(DTYPE, CPF, EMAIL, ID_DISCIPLINE, NAME) VALUES ('COISA', '079.831.369-27', 'EMAIL@GMAIL.COM', 509071355, 'não sei');
INSERT INTO TEACHER_MODEL(DTYPE, CPF, EMAIL, ID_DISCIPLINE, NAME) VALUES ('COISA', '079.831.369-27', 'EMAIL1@GMAIL.COM', 509071352, 'não sei');
INSERT INTO TEACHER_MODEL(DTYPE, CPF, EMAIL, ID_DISCIPLINE, NAME) VALUES ('COISA', '079.831.88822', 'EMAIL123@GMAIL.COM', 509071351, 'não sei');

INSERT INTO DISCIPLINE_MODEL (DESCRPTION_DISCIPLINE, NAME_DISCIPLINE) VALUES ('oi', 'Prog tbm');
INSERT INTO DISCIPLINE_MODEL (DESCRPTION_DISCIPLINE, NAME_DISCIPLINE) VALUES ('oi2', 'Prog tbm2');
INSERT INTO DISCIPLINE_MODEL (DESCRPTION_DISCIPLINE, NAME_DISCIPLINE) VALUES ('oi2', 'Prog tbm3');


INSERT INTO TEST_MODEL (NAME, ANSWERS, DATE_TIME) VALUES ('Prova de sip', '{"1":"C","2":"A","3":"D"}', TO_DATE('2023-04-11', 'yyyy-mm-dd'));
INSERT INTO TEST_MODEL (NAME, ANSWERS, DATE_TIME) VALUES ('Prova de The Winter', '{"1":"D","2":"E","3":"C"}',TO_DATE('2023-05-17', 'yyyy-mm-dd'));
INSERT INTO TEST_MODEL (NAME, ANSWERS, DATE_TIME) VALUES ('Prova de Sum', '{"1":"C","2":"A","3":"B"}', TO_DATE('2023-06-15', 'yyyy-mm-dd'));

INSERT INTO QUESTION_MODEL (QUESTION, ANSWERS, DIFFICULTY, CERTIFIED, ID_DISCIPLINE, ID_SUBJECT, AMOUNT_ACCESS, UPDATE_DATE) VALUES ('Porque o código funciona', 'Não sei o motivo exato, mas sei que o stackoverflow sabe', 1, 0, 1, 1, 0, TO_DATE('2023-04-11', 'yyyy-mm-dd'))
INSERT INTO QUESTION_MODEL (QUESTION, ANSWERS, DIFFICULTY, CERTIFIED, ID_DISCIPLINE, ID_SUBJECT, AMOUNT_ACCESS, UPDATE_DATE) VALUES ('Porque o código nunca funciona', 'Não sei o motivo exato, mas sei que o stackoverflow sabe', 2, 0, 3, 2,0,TO_DATE('2023-04-11', 'yyyy-mm-dd'))
INSERT INTO QUESTION_MODEL (QUESTION, ANSWERS, DIFFICULTY, CERTIFIED, ID_DISCIPLINE, ID_SUBJECT, AMOUNT_ACCESS, UPDATE_DATE) VALUES ('Porque eu não sei', 'Não sei o motivo exato, mas sei que o stackoverflow sabe', 4, 0, 2, 3,10,TO_DATE('2023-04-11', 'yyyy-mm-dd'))

INSERT INTO SUBJECT_MODEL (DESCRIPTION, AMOUNT_ACCESS, ID_DISCIPLINE) VALUES ('Algas', 0, 2);
INSERT INTO SUBJECT_MODEL (DESCRIPTION, AMOUNT_ACCESS, ID_DISCIPLINE) VALUES ('Rochas', 0, 1);
INSERT INTO SUBJECT_MODEL (DESCRIPTION, AMOUNT_ACCESS, ID_DISCIPLINE) VALUES ('Magma', 5, 3);




