-- MySQL Script generated by MySQL Workbench
-- Tue Feb 21 12:09:43 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Test` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Test` (
  `id_test` INT NOT NULL,
  `test_name` VARCHAR(45) NOT NULL,
  `test_date` DATE NOT NULL,
  `answers` VARCHAR(45) NULL,
  PRIMARY KEY (`id_test`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Discipline`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Discipline` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Discipline` (
  `id_discipline` INT NOT NULL,
  `discipline_name` VARCHAR(45) NOT NULL,
  `discipline_description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_discipline`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Subject` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Subject` (
  `id_subject` INT NOT NULL,
  `subject_description` VARCHAR(45) NOT NULL,
  `amount_access` INT NOT NULL,
  `Discipline_id_discipline` INT NOT NULL,
  PRIMARY KEY (`id_subject`),
  INDEX `fk_Subject_Discipline1_idx` (`Discipline_id_discipline` ASC) VISIBLE,
  CONSTRAINT `fk_Subject_Discipline1`
    FOREIGN KEY (`Discipline_id_discipline`)
    REFERENCES `mydb`.`Discipline` (`id_discipline`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Question` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Question` (
  `id_question` INT NOT NULL,
  `update_date` DATE NULL,
  `answer` VARCHAR(45) NOT NULL,
  `difficulty` INT NOT NULL,
  `certified` TINYINT NOT NULL,
  `amount_access` INT NOT NULL,
  `Discipline_id_discipline` INT NOT NULL,
  `Subject_id_subject` INT NOT NULL,
  PRIMARY KEY (`id_question`),
  INDEX `fk_Question_Discipline1_idx` (`Discipline_id_discipline` ASC) VISIBLE,
  INDEX `fk_Question_Subject1_idx` (`Subject_id_subject` ASC) VISIBLE,
  CONSTRAINT `fk_Question_Discipline1`
    FOREIGN KEY (`Discipline_id_discipline`)
    REFERENCES `mydb`.`Discipline` (`id_discipline`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Question_Subject1`
    FOREIGN KEY (`Subject_id_subject`)
    REFERENCES `mydb`.`Subject` (`id_subject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Student` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `id_student` INT NOT NULL,
  `student_cpf` VARCHAR(11) NOT NULL,
  `student_name` VARCHAR(45) NOT NULL,
  `student_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_student`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Teacher` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Teacher` (
  `id_teacher` INT NOT NULL,
  `teacher_cpf` VARCHAR(11) NOT NULL,
  `teacher_name` VARCHAR(45) NOT NULL,
  `teacher_email` VARCHAR(45) NOT NULL,
  `Discipline_id_discipline` INT NOT NULL,
  PRIMARY KEY (`id_teacher`),
  INDEX `fk_Teacher_Discipline1_idx` (`Discipline_id_discipline` ASC) VISIBLE,
  CONSTRAINT `fk_Teacher_Discipline1`
    FOREIGN KEY (`Discipline_id_discipline`)
    REFERENCES `mydb`.`Discipline` (`id_discipline`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Certifier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Certifier` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Certifier` (
  `amount_certified` INT NOT NULL,
  `Teacher_id_teacher` INT NOT NULL,
  PRIMARY KEY (`Teacher_id_teacher`),
  CONSTRAINT `fk_Certifier_Teacher1`
    FOREIGN KEY (`Teacher_id_teacher`)
    REFERENCES `mydb`.`Teacher` (`id_teacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Test_has_Question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Test_has_Question` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Test_has_Question` (
  `Test_id_test` INT NOT NULL,
  `Question_id_question` INT NOT NULL,
  PRIMARY KEY (`Test_id_test`, `Question_id_question`),
  INDEX `fk_Test_has_Question_Question1_idx` (`Question_id_question` ASC) VISIBLE,
  INDEX `fk_Test_has_Question_Test1_idx` (`Test_id_test` ASC) VISIBLE,
  CONSTRAINT `fk_Test_has_Question_Test1`
    FOREIGN KEY (`Test_id_test`)
    REFERENCES `mydb`.`Test` (`id_test`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Test_has_Question_Question1`
    FOREIGN KEY (`Question_id_question`)
    REFERENCES `mydb`.`Question` (`id_question`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Material` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Material` (
  `id_material` INT NOT NULL,
  `file_name` VARCHAR(45) NOT NULL,
  `content` VARCHAR(45) NOT NULL,
  `upload_date` DATE NOT NULL,
  `Teacher_id_teacher` INT NOT NULL,
  PRIMARY KEY (`id_material`),
  INDEX `fk_Material_Teacher1_idx` (`Teacher_id_teacher` ASC) VISIBLE,
  CONSTRAINT `fk_Material_Teacher1`
    FOREIGN KEY (`Teacher_id_teacher`)
    REFERENCES `mydb`.`Teacher` (`id_teacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teacher_has_Question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Teacher_has_Question` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Teacher_has_Question` (
  `Teacher_id_teacher` INT NOT NULL,
  `Question_id_question` INT NOT NULL,
  PRIMARY KEY (`Teacher_id_teacher`, `Question_id_question`),
  INDEX `fk_Teacher_has_Question_Question1_idx` (`Question_id_question` ASC) VISIBLE,
  INDEX `fk_Teacher_has_Question_Teacher1_idx` (`Teacher_id_teacher` ASC) VISIBLE,
  CONSTRAINT `fk_Teacher_has_Question_Teacher1`
    FOREIGN KEY (`Teacher_id_teacher`)
    REFERENCES `mydb`.`Teacher` (`id_teacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teacher_has_Question_Question1`
    FOREIGN KEY (`Question_id_question`)
    REFERENCES `mydb`.`Question` (`id_question`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student_has_Test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Student_has_Test` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Student_has_Test` (
  `Student_id_student` INT NOT NULL,
  `Test_id_test` INT NOT NULL,
  `result` DOUBLE NULL,
  PRIMARY KEY (`Student_id_student`, `Test_id_test`),
  INDEX `fk_Student_has_Test_Test1_idx` (`Test_id_test` ASC) VISIBLE,
  INDEX `fk_Student_has_Test_Student1_idx` (`Student_id_student` ASC) VISIBLE,
  CONSTRAINT `fk_Student_has_Test_Student1`
    FOREIGN KEY (`Student_id_student`)
    REFERENCES `mydb`.`Student` (`id_student`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_Test_Test1`
    FOREIGN KEY (`Test_id_test`)
    REFERENCES `mydb`.`Test` (`id_test`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Material_has_Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Material_has_Student` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Material_has_Student` (
  `Material_id_material` INT NOT NULL,
  `Student_id_student` INT NOT NULL,
  PRIMARY KEY (`Material_id_material`, `Student_id_student`),
  INDEX `fk_Material_has_Student_Student1_idx` (`Student_id_student` ASC) VISIBLE,
  INDEX `fk_Material_has_Student_Material1_idx` (`Material_id_material` ASC) VISIBLE,
  CONSTRAINT `fk_Material_has_Student_Material1`
    FOREIGN KEY (`Material_id_material`)
    REFERENCES `mydb`.`Material` (`id_material`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Material_has_Student_Student1`
    FOREIGN KEY (`Student_id_student`)
    REFERENCES `mydb`.`Student` (`id_student`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Certifier_has_Subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Certifier_has_Subject` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Certifier_has_Subject` (
  `Certifier_Teacher_id_teacher` INT NOT NULL,
  `Subject_id_subject` INT NOT NULL,
  PRIMARY KEY (`Certifier_Teacher_id_teacher`, `Subject_id_subject`),
  INDEX `fk_Certifier_has_Subject_Subject1_idx` (`Subject_id_subject` ASC) VISIBLE,
  INDEX `fk_Certifier_has_Subject_Certifier1_idx` (`Certifier_Teacher_id_teacher` ASC) VISIBLE,
  CONSTRAINT `fk_Certifier_has_Subject_Certifier1`
    FOREIGN KEY (`Certifier_Teacher_id_teacher`)
    REFERENCES `mydb`.`Certifier` (`Teacher_id_teacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Certifier_has_Subject_Subject1`
    FOREIGN KEY (`Subject_id_subject`)
    REFERENCES `mydb`.`Subject` (`id_subject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
